name: PyInstaller Package

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - { platform: x64, os: ubuntu-latest }
          - { platform: x64, os: windows-latest }
          - { platform: x86, os: windows-latest }
          - { platform: x64, os: macos-latest }

    name: main-${{ matrix.platform }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install -r requirements.txt

      - name: Build Package
        run: |
          pyinstaller "File Centipede Automatic Activation.spec"

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: Python-Package-${{ matrix.os }}-${{ matrix.platform }}
          path: dist/
