name: Pyinstaller UnpkgDownload

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - { platform: x64, os: ubuntu-latest }
          - { platform: x64, os: windows-latest }
          - { platform: x86, os: windows-latest }

    name: main-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 设置Python版本
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          architecture: ${{ matrix.platform }}
      
      - name: 安装Python依赖包
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install -r requirements.tx

      - name: 打包(只能是main.py)
        run: |
          pyinstaller -Fw main.py -i favicon.ico -n main-${{ matrix.os }}-${{ matrix.platform }}

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: Python-Package-${{ matrix.os }}-${{ matrix.platform }}
          path: dist/
