name: 使用nuitka进行打包

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - { platform: x64, os: windows-latest }
          # - { platform: x86, os: windows-latest }
          # - { platform: x64, os: ubuntu-latest }
          # - { platform: arm, os: ubuntu-latest }
          # - { platform: arm64, os: ubuntu-latest }
          # - { platform: armeb, os: ubuntu-latest }
          # - { platform: mips64el, os: ubuntu-latest }
          # - { platform: mipsel, os: ubuntu-latest }
          # - { platform: mips, os: ubuntu-latest }


    name: Build and Upload ${{ matrix.platform }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
  
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set Python version
      - name: Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.7.2'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: Install Nuitka
        run: pip install nuitka
      
      - name: Download UPX
        run: |
          python install_upx.py

      - name: Build the application
        run: echo "Yes" | python build_nuitka.py

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
